### ISSUE TITLE
update to version Magento-2.4.2 

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-magento#1]
Magento-2.4.1  released,please update to the latest version

**Comment by chendelin1982** [comment]
1. System Requirements: PHP7.4, MySQL 8.0, Composer 1.x and 2.x, Apache 2.4, PHP OPcache
2. Magento 2.4.2, it is recommended to use Elasticsearch 7.9.x. Magento 2.4.x is compatible with Elasticsearch 7.4 and above.
3. Install Varnish version 6.4, redis6.x, RabbitMQ 3.8.x but not need to configure
4. add version search

**Comment by chendelin1982** [comment]
administrator password: https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-subcommands-admin.html?itm_source=devdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=administrator%20password

**Comment by jiaosir-cn** [comment]
AWS aliyun  magento -d test ok

**Comment by qiaofeng1227** [comment]
Done
