### ISSUE TITLE
No password.txt

### ISSUE THREAD

**Issue by Kyle0791** [Websoft9/ansible-magento#10]
I try to use the Magento image in Tencent Cloud Market.
I have a problem finding the password for MySQL.
I couldn't find the "password.txt"
I went to the web "myIP/phpmyadmin/index.php"
I tried "root" as user name and "123456", "admin" "administrator", as password. All wrong.

**Comment by qiaofeng1227** [comment]
@Kyle0791 
I am sorry，Based on the above information, I can't locate the problem.
Can you provide the URL of our Magento product in Tencent Cloud Market?

Generally speaking, the password will be saved in this file：/credentials/password.txt

**Comment by qiaofeng1227** [comment]
长期没有回复，关闭
