### ISSUE TITLE
Installation initialization error

### ISSUE THREAD

**Issue by jiaosir-cn** [Websoft9/ansible-magento#5]
Project: Magento->Nginx->No, don't install it
Platform: AWS Linux2
ip: 34.207.155.254
Error Installation error
error:
```
TASK [role_redis : Install GCC for Redis6.0, refer to https://github.com/redis/redis/issues/7509] *********
fatal: [34.207.155.254]: FAILED! => {"changed": false, "msg": "No package matching 'devtoolset-7' found available, installed or updated", "rc": 126, "results": ["No package matching 'devtoolset-7' found available, installed or updated"]}
```
![image](https://user-images.githubusercontent.com/76861519/109093311-1bf58c00-7753-11eb-9c4f-4adf89af4709.png)

**Comment by qiaofeng1227** [comment]
transfer to:https://github.com/Websoft9/ansible-redis/issues/2
Done
