### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by jiaosir-cn** [Websoft9/ansible-magento#7]
**Describe the bug**

Installation error

ip:54.236.33.223

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [x] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [x] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [x] Aws
- [x] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

## Bug reproduce

5. other  Apache->Yes, install it
### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 
TASK [role_redis : Install GCC for Redis6.0, refer to https://github.com/redis/redis/issues/7509] *********
fatal: [54.236.33.223]: FAILED! => {"changed": false, "msg": "No package matching 'devtoolset-7' found available, installed or updated", "rc": 126, "results": ["No package matching 'devtoolset-7' found available, installed or updated"]}
# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
transfer to:Websoft9/ansible-redis#2
Done
