### ISSUE TITLE
Azure failed to generate swap partition 

### ISSUE THREAD

**Issue by hnczhjh** [Websoft9/ansible-magento#9]
#### 新机器的初始状态
[root@magento-0-CentOS7 websoft9]# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        1.9G     0  1.9G   0% /dev
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           1.9G  9.1M  1.9G   1% /run
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/sda2        30G  2.2G   27G   8% /
/dev/sda1       494M   75M  420M  16% /boot
/dev/sda15      495M   12M  484M   3% /boot/efi
/dev/sdb1       7.8G   36M  7.3G   1% /mnt/resource
tmpfs           379M     0  379M   0% /run/user/0
tmpfs           379M     0  379M   0% /run/user/1000

#### 跑过role_cloud之后：
[root@magento-jhqweqw-CentOS7 websoft9]# free -h
              total        used        free      shared  buff/cache   available
Mem:           3.7G        322M        3.2G        9.0M        149M        3.2G
Swap:            0B          0B          0B

[root@magento-0-CentOS7 websoft9]# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        1.9G     0  1.9G   0% /dev
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           1.9G  9.1M  1.9G   1% /run
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/sda2        30G  2.2G   27G   8% /
/dev/sda1       494M   75M  420M  16% /boot
/dev/sda15      495M   12M  484M   3% /boot/efi
/dev/sdb1       7.8G   36M  7.3G   1% /mnt/resource
tmpfs           379M     0  379M   0% /run/user/0
tmpfs           379M     0  379M   0% /run/user/1000

#### 2核4G安装magento之后：
[root@magento-jhqweqw-CentOS7 websoft9]# free -m
              total        used        free      shared  buff/cache   available
Mem:           3789         412        1789           9        1586        3106
Swap:             0           0           0

[root@magento-jht2-CentOS7 ansible-nodejs]# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        1.9G     0  1.9G   0% /dev
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           1.9G  9.5M  1.9G   1% /run
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/sda2        30G   11G   19G  38% /
/dev/sda1       494M   75M  419M  16% /boot
/dev/sda15      495M   12M  484M   3% /boot/efi
/dev/sdb1       7.8G   36M  7.3G   1% /mnt/resource
tmpfs           379M     0  379M   0% /run/user/1000
/dev/loop0       33M   33M     0 100% /var/lib/snapd/snap/snapd/12704
/dev/loop1       62M   62M     0 100% /var/lib/snapd/snap/core20/1081
/dev/loop2       43M   43M     0 100% /var/lib/snapd/snap/certbot/1343
overlay          30G   11G   19G  38% /var/lib/docker/overlay2/cc0565fac87d24ca6078abe6

**Comment by qiaofeng1227** [comment]
https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart

```
#!/bin/sh
if [ ! -f '/mnt/swapfile' ]; then
#fallocate --length 2GiB /mnt/swapfile
dd if=/dev/zero of=/mnt/swapfile bs=256M count=8
chmod 600 /mnt/swapfile
mkswap /mnt/swapfile
swapoff -a
swapon /mnt/swapfile
swapon -a 
else
swapon /mnt/swapfile; fi
```

chmod +x create_swapfile.sh
